//! Attestation Types
//!
//! Implements the combined TPM + TEE attestation report from Cordon spec §3.2 and §5.4.
//! In production, TPM quotes are generated by the TPM hardware and TEE quotes by the
//! AMD Secure Processor (SEV-SNP) or Intel SGX DCAP infrastructure.
//! This module provides the data structures and verification logic.

use std::collections::HashMap;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::error::{CryptoError, CryptoResult};
use crate::kdf::ct_eq;

/// TPM Platform Configuration Register (PCR) snapshot
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TpmPcrSet {
    /// Map from PCR index to SHA-256 hash value (hex)
    pub values: HashMap<u8, String>,
}

impl TpmPcrSet {
    /// Create an empty PCR set
    pub fn new() -> Self {
        Self { values: HashMap::new() }
    }

    /// Set a PCR value
    pub fn set(&mut self, index: u8, value: String) {
        self.values.insert(index, value);
    }

    /// Get a PCR value
    pub fn get(&self, index: u8) -> Option<&str> {
        self.values.get(&index).map(|s| s.as_str())
    }

    /// Verify this PCR set matches expected values
    pub fn verify_against(&self, expected: &TpmPcrSet) -> CryptoResult<()> {
        for (index, expected_val) in &expected.values {
            let actual = self.get(*index).ok_or_else(|| {
                CryptoError::AttestationFailed(format!("PCR[{}] missing from attestation report", index))
            })?;
            if !ct_eq(actual.as_bytes(), expected_val.as_bytes()) {
                return Err(CryptoError::PcrMismatch {
                    index: *index,
                    expected: expected_val.clone(),
                    actual: actual.to_string(),
                });
            }
        }
        Ok(())
    }
}

impl Default for TpmPcrSet {
    fn default() -> Self {
        Self::new()
    }
}

/// TPM Quote — signed snapshot of PCR values
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TpmQuote {
    /// PCR values at time of quote
    pub pcr_values: TpmPcrSet,
    /// TPM Attestation Identity Key public key (hex)
    pub aik_public_key_hex: String,
    /// Signature over quote data with AIK (hex)
    pub quote_signature_hex: String,
    /// Anti-replay nonce (base64), provided by client
    pub nonce: String,
    /// Quote timestamp
    pub timestamp: DateTime<Utc>,
    /// TPM endorsement key certificate chain (base64 DER)
    pub ek_cert_chain: Vec<String>,
}

/// TEE Measurement — enclave measurement from hardware
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TeeQuote {
    /// TEE type
    pub tee_type: TeeType,
    /// MRENCLAVE — measurement of code + data loaded into enclave
    pub mrenclave: String,
    /// MRSIGNER — measurement of the signer of the enclave
    pub mrsigner: String,
    /// ISV SVN (security version number)
    pub isv_svn: u16,
    /// Raw TEE attestation report (base64)
    pub raw_report_b64: String,
    /// Signature over report from hardware (AMD SP or Intel DCAP)
    pub report_signature_b64: String,
}

/// TEE technology type
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TeeType {
    /// Intel SGX v2
    IntelSgxV2,
    /// AMD SEV-SNP
    AmdSevSnp,
    /// ARM TrustZone
    ArmTrustZone,
    /// Software simulation (not for production)
    Simulation,
}

impl std::fmt::Display for TeeType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            TeeType::IntelSgxV2 => write!(f, "intel_sgx_v2"),
            TeeType::AmdSevSnp => write!(f, "amd_sev_snp"),
            TeeType::ArmTrustZone => write!(f, "arm_trustzone"),
            TeeType::Simulation => write!(f, "simulation"),
        }
    }
}

/// Combined attestation report — TPM PCR snapshot + TEE measurement
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CombinedAttestation {
    /// TPM quote
    pub tpm_quote: TpmQuote,
    /// TEE measurement
    pub tee_quote: TeeQuote,
    /// SHA-256 of (tpm_quote_bytes || tee_measurement_bytes)
    pub combined_hash: String,
    /// Cordon node ID
    pub node_id: String,
    /// Cordon version
    pub cordon_version: String,
    /// Report generation timestamp
    pub generated_at: DateTime<Utc>,
}

/// Expected measurements that a client configures at deployment time
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExpectedMeasurements {
    /// Expected PCR values
    pub pcr_values: TpmPcrSet,
    /// Expected MRENCLAVE value
    pub mrenclave: String,
    /// Expected MRSIGNER value
    pub mrsigner: String,
    /// Minimum ISV SVN
    pub min_isv_svn: u16,
    /// Accepted TEE type
    pub tee_type: TeeType,
}

/// Attestation report for client verification
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttestationReport {
    /// The combined attestation data
    pub combined: CombinedAttestation,
    /// Nonce the client issued (for anti-replay verification)
    pub client_nonce: String,
}

impl AttestationReport {
    /// Verify this attestation report against expected measurements.
    ///
    /// This implements the client-side verification from spec §5.3 Property 1.
    /// All checks must pass before releasing any key material.
    pub fn verify(&self, expected: &ExpectedMeasurements, client_nonce: &str) -> CryptoResult<()> {
        // 1. Verify nonce matches (anti-replay)
        if !ct_eq(
            self.combined.tpm_quote.nonce.as_bytes(),
            client_nonce.as_bytes(),
        ) {
            return Err(CryptoError::NonceMismatch);
        }

        // 2. Verify PCR values
        self.combined
            .tpm_quote
            .pcr_values
            .verify_against(&expected.pcr_values)?;

        // 3. Verify MRENCLAVE
        if !ct_eq(
            self.combined.tee_quote.mrenclave.as_bytes(),
            expected.mrenclave.as_bytes(),
        ) {
            return Err(CryptoError::EnclaveMeasurementMismatch {
                expected: expected.mrenclave.clone(),
                actual: self.combined.tee_quote.mrenclave.clone(),
            });
        }

        // 4. Verify MRSIGNER
        if !ct_eq(
            self.combined.tee_quote.mrsigner.as_bytes(),
            expected.mrsigner.as_bytes(),
        ) {
            return Err(CryptoError::AttestationFailed(format!(
                "MRSIGNER mismatch: expected {}, got {}",
                expected.mrsigner, self.combined.tee_quote.mrsigner
            )));
        }

        // 5. Verify ISV SVN >= minimum
        if self.combined.tee_quote.isv_svn < expected.min_isv_svn {
            return Err(CryptoError::AttestationFailed(format!(
                "ISV SVN {} below minimum {}",
                self.combined.tee_quote.isv_svn, expected.min_isv_svn
            )));
        }

        // 6. Verify TEE type matches
        if self.combined.tee_quote.tee_type != expected.tee_type {
            return Err(CryptoError::AttestationFailed(format!(
                "TEE type mismatch: expected {}, got {}",
                expected.tee_type, self.combined.tee_quote.tee_type
            )));
        }

        // Note: In production, steps 2 (TPM EK cert chain) and 3 (TPM quote signature)
        // from the spec are verified here using the TPM vendor CA certificates.
        // For the software implementation, we verify the combined hash integrity.
        self.verify_combined_hash()?;

        Ok(())
    }

    /// Verify the combined attestation hash integrity
    fn verify_combined_hash(&self) -> CryptoResult<()> {
        use sha2::{Digest, Sha256};
        use serde_json;

        let tpm_bytes = serde_json::to_vec(&self.combined.tpm_quote)
            .map_err(|e| CryptoError::Internal(e.to_string()))?;
        let tee_bytes = serde_json::to_vec(&self.combined.tee_quote)
            .map_err(|e| CryptoError::Internal(e.to_string()))?;

        let mut hasher = Sha256::new();
        hasher.update(&tpm_bytes);
        hasher.update(&tee_bytes);
        let computed = hex::encode(hasher.finalize());

        if !ct_eq(computed.as_bytes(), self.combined.combined_hash.as_bytes()) {
            return Err(CryptoError::AttestationFailed(
                "Combined attestation hash mismatch — report may be tampered".into(),
            ));
        }
        Ok(())
    }
}

/// Build a combined attestation hash from TPM and TEE quote bytes
pub fn compute_combined_hash(tpm_quote: &TpmQuote, tee_quote: &TeeQuote) -> CryptoResult<String> {
    use sha2::{Digest, Sha256};

    let tpm_bytes = serde_json::to_vec(tpm_quote)
        .map_err(|e| CryptoError::Internal(e.to_string()))?;
    let tee_bytes = serde_json::to_vec(tee_quote)
        .map_err(|e| CryptoError::Internal(e.to_string()))?;

    let mut hasher = Sha256::new();
    hasher.update(&tpm_bytes);
    hasher.update(&tee_bytes);
    Ok(hex::encode(hasher.finalize()))
}
